# This is a basic workflow to help you get started with Actions

name: test

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    - name: run core tests
      run: cd core && npm i && npm test
    - name: run ext tests
      run: cd vscode && npm i && npm test
